[2024-04-08T08:27:16.941+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:27:16.945+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:27:16.946+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:27:16.945+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:27:16.971+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:27:16.953+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:27:16.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:27:17.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.101 seconds
[2024-04-08T08:27:47.176+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:27:47.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:27:47.178+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:27:47.178+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:27:47.181+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:27:47.180+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:27:47.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:27:47.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.031 seconds
[2024-04-08T08:28:17.997+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:28:17.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:28:17.999+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:28:17.999+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:28:18.002+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:28:18.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:28:18.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:28:18.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.038 seconds
[2024-04-08T08:28:48.601+0000] {processor.py:161} INFO - Started process (PID=935) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:28:48.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:28:48.606+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:28:48.606+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:28:48.609+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:28:48.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:28:48.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:28:48.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.042 seconds
[2024-04-08T08:29:19.324+0000] {processor.py:161} INFO - Started process (PID=1193) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:29:19.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:29:19.325+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:29:19.325+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:29:19.328+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:29:19.327+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:29:19.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:29:19.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.036 seconds
[2024-04-08T08:29:49.676+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:29:49.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:29:49.678+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:29:49.678+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:29:49.682+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:29:49.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:29:49.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:29:49.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.029 seconds
[2024-04-08T08:30:20.190+0000] {processor.py:161} INFO - Started process (PID=1708) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:30:20.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:30:20.194+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:30:20.194+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:30:20.201+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:30:20.200+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:30:20.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:30:20.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.044 seconds
[2024-04-08T08:30:51.111+0000] {processor.py:161} INFO - Started process (PID=1965) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:30:51.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:30:51.113+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:30:51.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:30:51.115+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:30:51.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:30:51.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:30:51.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:31:21.747+0000] {processor.py:161} INFO - Started process (PID=2222) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:31:21.747+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:31:21.748+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:31:21.748+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:31:21.750+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:31:21.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:31:21.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:31:21.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:31:52.289+0000] {processor.py:161} INFO - Started process (PID=2479) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:31:52.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:31:52.290+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:31:52.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:31:52.292+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:31:52.292+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:31:52.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:31:52.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.026 seconds
[2024-04-08T08:32:22.875+0000] {processor.py:161} INFO - Started process (PID=2736) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:32:22.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:32:22.876+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:32:22.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:32:22.879+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:32:22.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:32:22.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:32:22.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:32:53.108+0000] {processor.py:161} INFO - Started process (PID=2993) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:32:53.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:32:53.110+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:32:53.109+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:32:53.112+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:32:53.112+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:32:53.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:32:53.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:33:23.566+0000] {processor.py:161} INFO - Started process (PID=3250) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:33:23.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:33:23.567+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:33:23.567+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:33:23.570+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:33:23.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:33:23.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:33:23.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.033 seconds
[2024-04-08T08:33:53.996+0000] {processor.py:161} INFO - Started process (PID=3507) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:33:53.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:33:53.998+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:33:53.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:33:54.002+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:33:54.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:33:54.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:33:54.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.036 seconds
[2024-04-08T08:34:24.375+0000] {processor.py:161} INFO - Started process (PID=3763) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:34:24.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:34:24.377+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:34:24.377+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:34:24.379+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:34:24.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:34:24.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:34:24.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:34:54.585+0000] {processor.py:161} INFO - Started process (PID=4020) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:34:54.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:34:54.586+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:34:54.586+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:34:54.588+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:34:54.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:34:54.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:34:54.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:35:25.106+0000] {processor.py:161} INFO - Started process (PID=4278) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:35:25.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:35:25.108+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:35:25.107+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:35:25.111+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:35:25.110+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:35:25.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:35:25.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.029 seconds
[2024-04-08T08:35:55.767+0000] {processor.py:161} INFO - Started process (PID=4535) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:35:55.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:35:55.768+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:35:55.768+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:35:55.770+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:35:55.770+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:35:55.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:35:55.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.026 seconds
[2024-04-08T08:36:26.296+0000] {processor.py:161} INFO - Started process (PID=4793) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:36:26.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:36:26.298+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:36:26.297+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:36:26.300+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:36:26.299+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:36:26.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:36:26.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:36:56.620+0000] {processor.py:161} INFO - Started process (PID=5050) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:36:56.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:36:56.622+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:36:56.622+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:36:56.624+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:36:56.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:36:56.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:36:56.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:37:27.001+0000] {processor.py:161} INFO - Started process (PID=5306) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:37:27.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:37:27.003+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:37:27.003+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:37:27.007+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:37:27.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:37:27.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:37:27.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.042 seconds
[2024-04-08T08:37:57.594+0000] {processor.py:161} INFO - Started process (PID=5563) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:37:57.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:37:57.596+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:37:57.595+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:37:57.599+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:37:57.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:37:57.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:37:57.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.059 seconds
[2024-04-08T08:38:28.207+0000] {processor.py:161} INFO - Started process (PID=5821) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:38:28.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:38:28.210+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:38:28.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:38:28.214+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:38:28.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:38:28.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:38:28.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.039 seconds
[2024-04-08T08:38:58.744+0000] {processor.py:161} INFO - Started process (PID=6078) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:38:58.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:38:58.748+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:38:58.747+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:38:58.751+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:38:58.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:38:58.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:38:58.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.041 seconds
[2024-04-08T08:39:29.473+0000] {processor.py:161} INFO - Started process (PID=6334) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:39:29.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:39:29.476+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:39:29.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:39:29.479+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:39:29.478+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:39:29.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:39:29.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.035 seconds
[2024-04-08T08:39:59.876+0000] {processor.py:161} INFO - Started process (PID=6591) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:39:59.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:39:59.878+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:39:59.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:39:59.880+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:39:59.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:39:59.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:39:59.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:40:30.256+0000] {processor.py:161} INFO - Started process (PID=6848) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:40:30.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:40:30.258+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:40:30.258+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:40:30.260+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:40:30.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:40:30.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:40:30.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.029 seconds
[2024-04-08T08:41:00.704+0000] {processor.py:161} INFO - Started process (PID=7105) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:41:00.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:41:00.705+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:41:00.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:41:00.708+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:41:00.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:41:00.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:41:00.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:41:31.307+0000] {processor.py:161} INFO - Started process (PID=7362) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:41:31.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:41:31.308+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:41:31.308+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:41:31.311+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:41:31.310+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:41:31.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:41:31.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:42:01.611+0000] {processor.py:161} INFO - Started process (PID=7619) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:42:01.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:42:01.614+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:42:01.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:42:01.617+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:42:01.616+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:42:01.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:42:01.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.038 seconds
[2024-04-08T08:42:31.978+0000] {processor.py:161} INFO - Started process (PID=7876) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:42:31.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:42:31.980+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:42:31.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:42:31.982+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:42:31.981+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:42:31.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:42:32.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:43:02.327+0000] {processor.py:161} INFO - Started process (PID=8133) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:43:02.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:43:02.329+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:43:02.329+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:43:02.331+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:43:02.331+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:43:02.332+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:43:02.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:43:32.865+0000] {processor.py:161} INFO - Started process (PID=8390) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:43:32.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:43:32.867+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:43:32.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:43:32.869+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:43:32.868+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:43:32.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:43:32.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:44:03.414+0000] {processor.py:161} INFO - Started process (PID=8647) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:44:03.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:44:03.415+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:44:03.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:44:03.418+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:44:03.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:44:03.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:44:03.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:44:34.051+0000] {processor.py:161} INFO - Started process (PID=8905) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:44:34.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:44:34.052+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:44:34.052+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:44:34.055+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:44:34.054+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:44:34.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:44:34.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:45:04.414+0000] {processor.py:161} INFO - Started process (PID=9164) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:45:04.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:45:04.416+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:45:04.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:45:04.418+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:45:04.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:45:04.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:45:04.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:45:34.777+0000] {processor.py:161} INFO - Started process (PID=9422) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:45:34.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:45:34.779+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:45:34.779+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:45:34.781+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:45:34.781+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:45:34.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:45:34.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:46:05.088+0000] {processor.py:161} INFO - Started process (PID=9679) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:46:05.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:46:05.089+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:46:05.089+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:46:05.092+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:46:05.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:46:05.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:46:05.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:46:35.455+0000] {processor.py:161} INFO - Started process (PID=9936) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:46:35.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:46:35.456+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:46:35.456+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:46:35.459+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:46:35.459+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:46:35.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:46:35.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.035 seconds
[2024-04-08T08:47:06.047+0000] {processor.py:161} INFO - Started process (PID=10193) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:47:06.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:47:06.049+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:47:06.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:47:06.053+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:47:06.052+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:47:06.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:47:06.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.039 seconds
[2024-04-08T08:47:36.157+0000] {processor.py:161} INFO - Started process (PID=10450) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:47:36.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:47:36.158+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:47:36.158+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:47:36.161+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:47:36.160+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:47:36.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:47:36.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:48:06.351+0000] {processor.py:161} INFO - Started process (PID=10707) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:48:06.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:48:06.353+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:48:06.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:48:06.355+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:48:06.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:48:06.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:48:06.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:48:36.898+0000] {processor.py:161} INFO - Started process (PID=10964) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:48:36.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:48:36.900+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:48:36.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:48:36.902+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:48:36.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:48:36.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:48:36.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:49:07.282+0000] {processor.py:161} INFO - Started process (PID=11221) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:49:07.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:49:07.284+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:49:07.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:49:07.286+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:49:07.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:49:07.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:49:07.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:49:37.696+0000] {processor.py:161} INFO - Started process (PID=11478) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:49:37.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:49:37.697+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:49:37.697+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:49:37.699+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:49:37.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:49:37.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:49:37.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:50:08.202+0000] {processor.py:161} INFO - Started process (PID=11736) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:50:08.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:50:08.204+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:50:08.203+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:50:08.206+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:50:08.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:50:08.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:50:08.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:50:38.766+0000] {processor.py:161} INFO - Started process (PID=11992) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:50:38.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:50:38.767+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:50:38.767+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:50:38.770+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:50:38.769+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:50:38.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:50:38.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:51:09.181+0000] {processor.py:161} INFO - Started process (PID=12250) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:51:09.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:51:09.183+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:51:09.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:51:09.185+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:51:09.184+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:51:09.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:51:09.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:51:39.653+0000] {processor.py:161} INFO - Started process (PID=12508) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:51:39.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:51:39.654+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:51:39.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:51:39.656+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:51:39.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:51:39.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:51:39.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.033 seconds
[2024-04-08T08:52:09.986+0000] {processor.py:161} INFO - Started process (PID=12765) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:52:09.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:52:09.988+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:52:09.988+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:52:09.991+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:52:09.991+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:52:09.992+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:52:10.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.063 seconds
[2024-04-08T08:52:40.622+0000] {processor.py:161} INFO - Started process (PID=13022) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:52:40.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:52:40.623+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:52:40.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:52:40.626+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:52:40.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:52:40.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:52:40.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:53:11.204+0000] {processor.py:161} INFO - Started process (PID=13279) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:53:11.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:53:11.206+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:53:11.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:53:11.208+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:53:11.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:53:11.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:53:11.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:53:41.468+0000] {processor.py:161} INFO - Started process (PID=13536) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:53:41.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:53:41.470+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:53:41.470+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:53:41.473+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:53:41.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:53:41.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:53:41.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.032 seconds
[2024-04-08T08:54:12.088+0000] {processor.py:161} INFO - Started process (PID=13800) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:54:12.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:54:12.090+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:54:12.090+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:54:12.092+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:54:12.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:54:12.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:54:12.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:54:42.501+0000] {processor.py:161} INFO - Started process (PID=14058) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:54:42.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:54:42.502+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:54:42.502+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:54:42.504+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:54:42.504+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:54:42.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:54:42.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
[2024-04-08T08:55:12.853+0000] {processor.py:161} INFO - Started process (PID=14316) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:55:12.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:55:12.854+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:55:12.854+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:55:12.856+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:55:12.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:55:12.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:55:12.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.028 seconds
[2024-04-08T08:55:43.238+0000] {processor.py:161} INFO - Started process (PID=14574) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:55:43.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:55:43.239+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:55:43.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:55:43.242+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:55:43.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:55:43.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:55:43.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.032 seconds
[2024-04-08T08:56:13.542+0000] {processor.py:161} INFO - Started process (PID=14832) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:56:13.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:56:13.544+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:56:13.544+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:56:13.547+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:56:13.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:56:13.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:56:13.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.035 seconds
[2024-04-08T08:56:43.954+0000] {processor.py:161} INFO - Started process (PID=15089) to work on /opt/airflow/dags/hello.py
[2024-04-08T08:56:43.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/hello.py for tasks to queue
[2024-04-08T08:56:43.956+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:56:43.956+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/hello.py
[2024-04-08T08:56:43.958+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:56:43.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello.py", line 29
    say_hello = PythonOperator(
    ^
IndentationError: unexpected indent
[2024-04-08T08:56:43.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/hello.py
[2024-04-08T08:56:43.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/hello.py took 0.027 seconds
